### ISSUE TITLE
Exception when trying to load lcov.info over STDIN

### ISSUE THREAD

**Issue by tubbo** [codeclimate/javascript-test-reporter#16]
After generating an lcov.info using `istanbul report lcovonly`, I tried the command the README told me to do (`codeclimate < coverage/lcov.info`) and got this error:

```
/Users/necromancer/Code/psychedeli.ca/node_modules/codeclimate-test-reporter/formatter.js:53
  data.forEach(function(elem, index) {
       ^
TypeError: Cannot call method 'forEach' of undefined
    at Formatter.sourceFiles (/Users/necromancer/Code/psychedeli.ca/node_modules/codeclimate-test-reporter/formatter.js:53:8)
    at /Users/necromancer/Code/psychedeli.ca/node_modules/codeclimate-test-reporter/formatter.js:22:26
    at walkFile (/Users/necromancer/Code/psychedeli.ca/node_modules/codeclimate-test-reporter/node_modules/lcov-parse/lib/index.js:105:9)
    at /Users/necromancer/Code/psychedeli.ca/node_modules/codeclimate-test-reporter/node_modules/lcov-parse/lib/index.js:112:20
    at Object.cb [as oncomplete] (fs.js:169:19)
```

I also tried the alternative `cat coverage/lcov.info | codeclimate` syntax.

I am using codeclimate-test-reporter v0.0.4 on node.js v0.10.35.

**Comment by andrewvaughan** [comment]
I also have experienced this issue as shown.

**Comment by dblandin** [comment]
Hi @tubbo, are you still experiencing this issue?

**Comment by dblandin** [comment]
I'm going to close this issue for now. Feel free to reopen if this is still occurring.
